name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
      env:
        SECRET: ${{ secrets.SuperSecret }}
    - name: Build the Docker image "$SECRET"     
      run: docker build . --no-cache --file Dockerfile --tag wsbu/esp-idf:$(date +%s) --build-arg SSH_KEY="$SECRET"
